# This is a comment
service: upload
runtime: nodejs12
instance_class: F2
automatic_scaling:
  max_instances: 2
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8
  min_pending_latency: 50ms 
  max_pending_latency: 1000ms
  max_concurrent_requests: 10


handlers:
- url: /favicon\.ico
  static_files: /out/static/favicon.ico
  upload: out/static/favicon\.ico

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto


error_handlers:
  - error_code: timeout
    file: timeout_error.json





